### ISSUE TITLE
Please update repo description to mention dependence on JQuery

### ISSUE THREAD

**Issue by dandv** [divyanshu-rawat/JQuery-widget#1]
.or consider dropping jQuery, since there are so [many](https://github.com/aaronpk/rating-stars) [rating widgets](https://github.com/juliangruber/rating) that don't need jQuery and offer [rich UX](https://github.com/LunarLogic/starability).

**Comment by divyanshu-rawat** [comment]
JQuery was already added as a dependencies in bower.json but I forgot to written it in readme.md.
Anyways Now I have updated repo. description to mention dependence on JQuery.
Thnx for suggesting
